// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Curry = require("bs-platform/lib/js/curry.js");
var $$String = require("bs-platform/lib/js/string.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

function getLines($staropt$star, path) {
  var splitBy = $staropt$star !== undefined ? $staropt$star : /* "\n" */10;
  var __x = $$String.split_on_char(splitBy, Fs.readFileSync(path, "utf8"));
  return Belt_List.keep(__x, (function (s) {
                return s.length !== 0;
              }));
}

function $great$great(f, g, x) {
  return Curry._1(g, Curry._1(f, x));
}

function sumListBy(input, f) {
  return Belt_List.reduce(Belt_List.map(input, (function (param) {
                    return Curry._1(f, Caml_format.caml_int_of_string(param));
                  })), 0, (function (prim, prim$1) {
                return prim + prim$1 | 0;
              }));
}

exports.getLines = getLines;
exports.$great$great = $great$great;
exports.sumListBy = sumListBy;
/* fs Not a pure module */
